<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_CheckboxByText</name>
   <tag></tag>
   <elementGuidId>28efa7c5-4710-4538-93a5-7df76d292788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='form-checkbox-item']/input)[@value='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='form-checkbox-item']/input)[@value='${text}']</value>
   </webElementProperties>
</WebElementEntity>
